name: build and deploy Chinese book to gh-pages

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Install expect
      run: sudo apt-get install -y expect

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.4

    - name: Setup elan toolchain on this build
      run: |
        curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
        chmod u+x elan-init.sh
        ./elan-init.sh -y --default-toolchain none

    - name: Set elan paths
      run: |
        echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

    - name: Install lean toolchain for examples
      run: |
        cd examples
        lean --version

    - name: Install lean toolchain for Chinese book
      run: |
        cd book_zh
        lean --version

    - name: Cache examples/.lake
      uses: actions/cache@v4
      with:
        path: examples/.lake
        # The SHA is in the key to get the most recent cache possible, rather than just saving a single one for each Lean/deps version and not touching it.
        key: ${{ runner.os }}-${{ hashFiles('examples/lake-manifest.json') }}-${{ hashFiles('examples/lean-toolchain') }}-${{ github.sha }}
        # Try to restore cache for same OS/Lean/deps, but don't get less specific, because Lake isn't always happy to get build product version mismatches
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('examples/lake-manifest.json') }}-${{ hashFiles('examples/lean-toolchain') }}-

    - name: Cache book_zh/.lake
      uses: actions/cache@v4
      with:
        path: book_zh/.lake
        # The SHA is in the key to get the most recent cache possible, rather than just saving a single one for each Lean/deps version and not touching it.
        key: ${{ runner.os }}-${{ hashFiles('book_zh/lake-manifest.json') }}-${{ hashFiles('book_zh/lean-toolchain') }}-${{ github.sha }}
        # Try to restore cache for same OS/Lean/deps, but don't get less specific, because Lake isn't always happy to get build product version mismatches
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('book_zh/lake-manifest.json') }}-${{ hashFiles('book_zh/lean-toolchain') }}-

    - name: Build example code
      run: |
        pushd examples
        lake build
        lake build subverso-extract-mod
        popd

    - name: Save examples/.lake
      uses: actions/cache/save@v4
      with:
        path: examples/.lake
        # The SHA is in the key to get the most recent cache possible, rather than just saving a single one for each Lean/deps version and not touching it.
        key: ${{ runner.os }}-${{ hashFiles('examples/lake-manifest.json') }}-${{ hashFiles('examples/lean-toolchain') }}-${{ github.sha }}

    - name: Build Chinese book
      run: |
        pushd book_zh
        lake exe fp-lean --depth 2 --without-html-single --verbose
        popd

    - name: Save book_zh/.lake
      uses: actions/cache/save@v4
      with:
        path: book_zh/.lake
        # The SHA is in the key to get the most recent cache possible, rather than just saving a single one for each Lean/deps version and not touching it.
        key: ${{ runner.os }}-${{ hashFiles('book_zh/lake-manifest.json') }}-${{ hashFiles('book_zh/lean-toolchain') }}-${{ github.sha }}

    # This is to get the cached highlight JSON files
    - name: Save examples/.lake again
      uses: actions/cache/save@v4
      with:
        path: examples/.lake
        # The SHA is in the key to get the most recent cache possible, rather than just saving a single one for each Lean/deps version and not touching it.
        key: ${{ runner.os }}-${{ hashFiles('examples/lake-manifest.json') }}-${{ hashFiles('examples/lean-toolchain') }}-${{ github.sha }}


    - name: Deploy Chinese book to gh-pages
      if: github.event_name == 'push' && github.ref_name == 'master'
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: book_zh/_out/html-multi
